/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package soccerTeam.view;

import javax.swing.JOptionPane;
import soccerTeam.control.SoccerTeamController;
import soccerTeam.logic.exceptions.NoGenderException;

/**
 *
 * @author Arianne
 */
public class FirstTimeSetupUI extends javax.swing.JFrame {

    private SoccerTeamController stc;
    
    /**
     * Creates new form FirstTimeSetupUI
     */
    public FirstTimeSetupUI(SoccerTeamController stc) {
        this.stc = stc;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setupPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        associationNameField = new javax.swing.JTextField();
        associationStreetField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        associationHousenumberField = new javax.swing.JTextField();
        associationcityField = new javax.swing.JTextField();
        associationZipcodeField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        setupFinishButton = new javax.swing.JButton();
        associationExitButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        teamNameField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        coachNameField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        coachMaleRadioButton = new javax.swing.JRadioButton();
        coachFemaleRadioButton = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        coachHousenumberField = new javax.swing.JTextField();
        coachCityField = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        coachZipcodeField = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        coachPhonenumberField = new javax.swing.JTextField();
        coachCheckBox = new javax.swing.JCheckBox();
        coachStreetField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        associationPhonenumberField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("First Time Setup");

        jLabel1.setText("Welcome to \"Program name\". ");

        jLabel2.setText("Please enter the required information below to setup this program.");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Soccer Association :");

        jLabel4.setText("Association Name :");

        jLabel5.setText("Street :");

        associationStreetField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                associationStreetFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("Number :");

        associationcityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                associationcityFieldActionPerformed(evt);
            }
        });

        jLabel7.setText("City :");

        jLabel8.setText("Zipcode :");

        setupFinishButton.setText("Finish");
        setupFinishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setupFinishButtonActionPerformed(evt);
            }
        });

        associationExitButton.setText("Exit");
        associationExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                associationExitButtonActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Soccer Team :");

        jLabel10.setText("Team Name :");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Coach :");

        jLabel20.setText("Name :");

        jLabel21.setText("Gender : ");

        coachMaleRadioButton.setText("Male");

        coachFemaleRadioButton.setText("Female");

        jLabel22.setText("Street :");

        jLabel23.setText("Number :");

        coachCityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coachCityFieldActionPerformed(evt);
            }
        });

        jLabel24.setText("City :");

        jLabel25.setText("Zipcode :");

        jLabel26.setText("Phonenr. :");

        coachCheckBox.setText("Yes, I am the coach of this soccerteam of this soccer association.");
        coachCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coachCheckBoxActionPerformed(evt);
            }
        });

        coachStreetField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coachStreetFieldActionPerformed(evt);
            }
        });

        jLabel11.setText("Phonenumber :");

        javax.swing.GroupLayout setupPanelLayout = new javax.swing.GroupLayout(setupPanel);
        setupPanel.setLayout(setupPanelLayout);
        setupPanelLayout.setHorizontalGroup(
            setupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setupPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(setupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, setupPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(setupFinishButton)
                        .addGap(18, 18, 18)
                        .addComponent(associationExitButton))
                    .addGroup(setupPanelLayout.createSequentialGroup()
                        .addGroup(setupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel2)
                            .addComponent(jLabel21)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(coachCheckBox)
                            .addComponent(jLabel14)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel9))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(setupPanelLayout.createSequentialGroup()
                        .addGroup(setupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel20)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(21, 21, 21)
                        .addGroup(setupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(associationPhonenumberField)
                            .addComponent(associationNameField)
                            .addGroup(setupPanelLayout.createSequentialGroup()
                                .addComponent(associationStreetField, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(associationHousenumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(teamNameField)
                            .addComponent(coachPhonenumberField)
                            .addComponent(coachNameField)
                            .addGroup(setupPanelLayout.createSequentialGroup()
                                .addComponent(coachZipcodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(coachCityField))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, setupPanelLayout.createSequentialGroup()
                                .addComponent(coachStreetField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(coachHousenumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(setupPanelLayout.createSequentialGroup()
                                .addComponent(coachFemaleRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(coachMaleRadioButton)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(setupPanelLayout.createSequentialGroup()
                                .addComponent(associationZipcodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(associationcityField)))))
                .addContainerGap())
        );
        setupPanelLayout.setVerticalGroup(
            setupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setupPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(setupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(associationNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(setupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(associationHousenumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(associationStreetField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(setupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(associationZipcodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(associationcityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(setupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(associationPhonenumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(setupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(teamNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(setupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(coachNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(setupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(coachFemaleRadioButton)
                    .addComponent(coachMaleRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(setupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(coachStreetField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coachHousenumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(setupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(coachZipcodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coachCityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(setupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(coachPhonenumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(coachCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(setupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(associationExitButton)
                    .addComponent(setupFinishButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(setupPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(setupPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void associationcityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_associationcityFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_associationcityFieldActionPerformed

    private void associationStreetFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_associationStreetFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_associationStreetFieldActionPerformed

    private void setupFinishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setupFinishButtonActionPerformed
        String associationName = this.associationNameField.getText();
        String associationStreet = this.associationStreetField.getText();
        String associationHousenumber = this.associationHousenumberField.getText();
        String associationZipcode = this.associationZipcodeField.getText();
        String associationCity = this.associationcityField.getText();
        String associationPhonenumber = this.associationPhonenumberField.getText();
        
        String teamName = this.teamNameField.getText();
        
        String coachName = this.coachNameField.getText();
        String coachStreet = this.coachStreetField.getText();
        String coachHousenumber = this.coachHousenumberField.getText();
        String coachZipcode = this.coachZipcodeField.getText();
        String coachCity = this.coachCityField.getText();
        String coachPhonenumber = this.coachPhonenumberField.getText();
        
        boolean isCoach = this.coachCheckBox.isEnabled(); //has to be true
        try{
            boolean coachGender = this.getMaleFemaleRadioButtonGroup();
            if(associationName.isEmpty()){
                JOptionPane.showMessageDialog(this, "Please enter association name.");
            } else if(associationStreet.isEmpty()){
                JOptionPane.showMessageDialog(this, "Please enter association street.");
            } else if(associationHousenumber.isEmpty()){
                JOptionPane.showMessageDialog(this, "Please enter association housenumber.");
            } else if(associationZipcode.isEmpty()){
                JOptionPane.showMessageDialog(this, "Please enter association zipcode.");
            } else if(associationCity.isEmpty()){
                JOptionPane.showMessageDialog(this, "Please enter association city.");
            } else if(associationPhonenumber.isEmpty()){
                JOptionPane.showMessageDialog(this, "Please enter association phonenumber.");
            } else if(teamName.isEmpty()){
                JOptionPane.showMessageDialog(this, "Please enter a team name");
            } else if(coachName.isEmpty()){
                JOptionPane.showMessageDialog(this, "Please enter the coaches name.");
            } else if(coachStreet.isEmpty()){
                JOptionPane.showMessageDialog(this, "Please enter the coaches street.");
            } else if(coachHousenumber.isEmpty()){
                JOptionPane.showMessageDialog(this, "Please enter the coaches housenumber.");
            } else if(coachZipcode.isEmpty()){
                JOptionPane.showMessageDialog(this, "Please enter the coaches zipcode.");
            } else if(coachCity.isEmpty()){
                JOptionPane.showMessageDialog(this, "Please enter the coaches city.");
            } else if(coachPhonenumber.isEmpty()){
                JOptionPane.showMessageDialog(this, "Please enter the coaches phonenumber.");
            }if(!isCoach){
                JOptionPane.showMessageDialog(this, "You must be a coach to setup this program.");
            } else {
                this.stc.createModel(associationName, associationStreet, associationHousenumber, 
                        associationZipcode, associationCity, associationPhonenumber, teamName,
                        coachName, coachGender, coachStreet, coachHousenumber, coachZipcode,
                        coachCity, coachPhonenumber);
            }
            } catch (NoGenderException ex){
            JOptionPane.showMessageDialog(this, "Please enter the coaches gender");
        }
        

    }//GEN-LAST:event_setupFinishButtonActionPerformed

    private void coachStreetFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coachStreetFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coachStreetFieldActionPerformed

    private void coachCityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coachCityFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coachCityFieldActionPerformed

    private void coachCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coachCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coachCheckBoxActionPerformed

    private void associationExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_associationExitButtonActionPerformed
        this.stc.exit();
    }//GEN-LAST:event_associationExitButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton associationExitButton;
    private javax.swing.JTextField associationHousenumberField;
    private javax.swing.JTextField associationNameField;
    private javax.swing.JTextField associationPhonenumberField;
    private javax.swing.JTextField associationStreetField;
    private javax.swing.JTextField associationZipcodeField;
    private javax.swing.JTextField associationcityField;
    private javax.swing.JCheckBox coachCheckBox;
    private javax.swing.JTextField coachCityField;
    private javax.swing.JRadioButton coachFemaleRadioButton;
    private javax.swing.JTextField coachHousenumberField;
    private javax.swing.JRadioButton coachMaleRadioButton;
    private javax.swing.JTextField coachNameField;
    private javax.swing.JTextField coachPhonenumberField;
    private javax.swing.JTextField coachStreetField;
    private javax.swing.JTextField coachZipcodeField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton setupFinishButton;
    private javax.swing.JPanel setupPanel;
    private javax.swing.JTextField teamNameField;
    // End of variables declaration//GEN-END:variables

    private boolean getMaleFemaleRadioButtonGroup() throws NoGenderException {
        throw new UnsupportedOperationException("Not yet implemented");
    }
}
