/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package soccerTeam.view;

/**
 *
 * @author Arianne
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginGegevens = new javax.swing.JDialog();
        loginGegevensGebruikersnaamLabel = new javax.swing.JLabel();
        loginGegevensWachtwoordPanel = new javax.swing.JLabel();
        loginGegevensGebruikersnaamField = new javax.swing.JTextField();
        loginGegevensWachtwoordField = new javax.swing.JTextField();
        LoginGegevensOKButton = new javax.swing.JButton();
        loginGegevensWijzigButton = new javax.swing.JButton();
        spelerToevoegen = new javax.swing.JDialog();
        spelerToevoegenStraatLabel = new javax.swing.JLabel();
        spelerToevoegenNaamLabel = new javax.swing.JLabel();
        spelerToevoegenNaamField = new javax.swing.JTextField();
        spelerToevoegenGeslachtLabel = new javax.swing.JLabel();
        spelerToevoegenGeslachtManRadioButton = new javax.swing.JRadioButton();
        spelerToevoegenGeslachtVrouwRadioButton = new javax.swing.JRadioButton();
        spelerToevoegenStraatField = new javax.swing.JTextField();
        spelerToevoegenHuisnummerField = new javax.swing.JTextField();
        spelerToevoegenPlaatsField = new javax.swing.JTextField();
        spelerToevoegenprofielPostcodeField = new javax.swing.JTextField();
        spelerToevoegenprofielPlaatsLabel = new javax.swing.JLabel();
        spelerToevoegenHuisnummerLabel = new javax.swing.JLabel();
        spelerToevoegenPostcodeLabel = new javax.swing.JLabel();
        spelerToevoegenTelefoonnummerLabel = new javax.swing.JLabel();
        spelerToevoegenprofielEmailLabel = new javax.swing.JLabel();
        spelerToevoegenEmailField = new javax.swing.JTextField();
        spelerToevoegenTelefoonnummerField = new javax.swing.JTextField();
        spelerToevoegenClearButton = new javax.swing.JButton();
        spelerToevoegenVoegToeButton = new javax.swing.JButton();
        spelerToevoegenAnnulerenButton = new javax.swing.JButton();
        firstTime = new javax.swing.JDialog();
        spelerToevoegenNaamField1 = new javax.swing.JTextField();
        spelerToevoegenNaamLabel1 = new javax.swing.JLabel();
        spelerToevoegenGeslachtLabel1 = new javax.swing.JLabel();
        spelerToevoegenStraatLabel1 = new javax.swing.JLabel();
        spelerToevoegenPostcodeLabel1 = new javax.swing.JLabel();
        spelerToevoegenTelefoonnummerLabel1 = new javax.swing.JLabel();
        spelerToevoegenprofielEmailLabel1 = new javax.swing.JLabel();
        spelerToevoegenEmailField1 = new javax.swing.JTextField();
        spelerToevoegenTelefoonnummerField1 = new javax.swing.JTextField();
        spelerToevoegenprofielPostcodeField1 = new javax.swing.JTextField();
        spelerToevoegenGeslachtManRadioButton1 = new javax.swing.JRadioButton();
        spelerToevoegenGeslachtVrouwRadioButton1 = new javax.swing.JRadioButton();
        spelerToevoegenStraatField1 = new javax.swing.JTextField();
        spelerToevoegenHuisnummerLabel1 = new javax.swing.JLabel();
        spelerToevoegenHuisnummerField1 = new javax.swing.JTextField();
        spelerToevoegenPlaatsField1 = new javax.swing.JTextField();
        spelerToevoegenVoegToeButton1 = new javax.swing.JButton();
        spelerToevoegenAnnulerenButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        wedstrijdTeamAanmaken = new javax.swing.JDialog();
        wedstrijdTeamAanmakenGekozenTeamScrollPane = new javax.swing.JScrollPane();
        wedstrijdTeamAanmakenGekozenTeamList = new javax.swing.JList();
        wedstrijdTeamAanmakenBeschikbareSpelersScrollPane = new javax.swing.JScrollPane();
        wedstrijdTeamAanmakenBeschikbareSpelersList = new javax.swing.JList();
        wedstrijdTeamAanmakenBeschikbareSpelersLabel = new javax.swing.JLabel();
        wedstrijdTeamAanmakenGekozenTeamLabel = new javax.swing.JLabel();
        wedstrijdTeamAanmakenKiesButton = new javax.swing.JButton();
        wedstrijdTeamAanmakenVerwijderButton = new javax.swing.JButton();
        wedstrijdTeamAanmakenAnnulerenButton = new javax.swing.JButton();
        wedstrijdTeamAanmakenOpslaanButton = new javax.swing.JButton();
        tabbedPane = new javax.swing.JTabbedPane();
        welkomTab = new javax.swing.JPanel();
        profielTab = new javax.swing.JPanel();
        profielNaamLabel = new javax.swing.JLabel();
        profielGeslachtLabel = new javax.swing.JLabel();
        profielStraatLabel = new javax.swing.JLabel();
        profielHuisnummerLabel = new javax.swing.JLabel();
        profielPostcodeLabel = new javax.swing.JLabel();
        profielPlaatsLabel = new javax.swing.JLabel();
        profielTelefoonnummerLabel = new javax.swing.JLabel();
        profielEmailLabel = new javax.swing.JLabel();
        profielNaamField = new javax.swing.JTextField();
        profielStraatField = new javax.swing.JTextField();
        profielHuisnummerField = new javax.swing.JTextField();
        profielPostcodeField = new javax.swing.JTextField();
        profielPlaatsField = new javax.swing.JTextField();
        profielTelefoonnummerField = new javax.swing.JTextField();
        profielEmailField = new javax.swing.JTextField();
        profielGeslachtManRadioButton = new javax.swing.JRadioButton();
        profielGeslachtVrouwRadioButton = new javax.swing.JRadioButton();
        profielLoguitButton = new javax.swing.JButton();
        profielWijzigButton = new javax.swing.JButton();
        profielLoginGegevensButton = new javax.swing.JButton();
        beschikbaarheidTab = new javax.swing.JPanel();
        beschikbaarheidWedstrijdenScrollPane = new javax.swing.JScrollPane();
        beschikbaarheidWedstrijdenList = new javax.swing.JList();
        jLabel6 = new javax.swing.JLabel();
        statistiekenToevoegenTab = new javax.swing.JPanel();
        statistiekenToevoegenToevoegenButton = new javax.swing.JButton();
        statistiekenToevoegenClearButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        teamTab = new javax.swing.JPanel();
        teamSpelerToevoegenButton = new javax.swing.JButton();
        teamWedstrijdToevoegenButton = new javax.swing.JButton();
        teamCapainAanwijzenButton = new javax.swing.JButton();
        teamKeeperAanwijzenButton = new javax.swing.JButton();
        teamSpelerOpvragenButton = new javax.swing.JButton();
        teamWedstrijdTeamAanmakenButton = new javax.swing.JButton();
        teamWedstrijdTeamWijzigenButton = new javax.swing.JButton();
        teamTeamLabel = new javax.swing.JLabel();
        teamWedstrijdLabel = new javax.swing.JLabel();
        teamStatistiekenBekijkenButton = new javax.swing.JButton();
        teamAankomendeWedstrijdenButton = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        optionsMenu = new javax.swing.JMenu();
        logoffMenuItem = new javax.swing.JMenuItem();
        loginMenuItem = new javax.swing.JMenuItem();
        toggleFullscreenMenuItem = new javax.swing.JRadioButtonMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();

        loginGegevens.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        loginGegevens.setTitle("Login Gegevens");

        loginGegevensGebruikersnaamLabel.setText("Gebruikersnaam :");

        loginGegevensWachtwoordPanel.setText("Wachtwoord :");

        LoginGegevensOKButton.setText("OK");

        loginGegevensWijzigButton.setText("Wijzig");

        javax.swing.GroupLayout loginGegevensLayout = new javax.swing.GroupLayout(loginGegevens.getContentPane());
        loginGegevens.getContentPane().setLayout(loginGegevensLayout);
        loginGegevensLayout.setHorizontalGroup(
            loginGegevensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginGegevensLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginGegevensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginGegevensLayout.createSequentialGroup()
                        .addGap(0, 174, Short.MAX_VALUE)
                        .addComponent(loginGegevensWijzigButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LoginGegevensOKButton))
                    .addGroup(loginGegevensLayout.createSequentialGroup()
                        .addGroup(loginGegevensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginGegevensGebruikersnaamLabel)
                            .addComponent(loginGegevensWachtwoordPanel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(loginGegevensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginGegevensWachtwoordField)
                            .addComponent(loginGegevensGebruikersnaamField))))
                .addContainerGap())
        );
        loginGegevensLayout.setVerticalGroup(
            loginGegevensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginGegevensLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginGegevensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginGegevensGebruikersnaamLabel)
                    .addComponent(loginGegevensGebruikersnaamField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loginGegevensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginGegevensWachtwoordPanel)
                    .addComponent(loginGegevensWachtwoordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loginGegevensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginGegevensOKButton)
                    .addComponent(loginGegevensWijzigButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        spelerToevoegen.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        spelerToevoegen.setTitle("Speler Toevoegen");

        spelerToevoegenStraatLabel.setText("Straat :");

        spelerToevoegenNaamLabel.setText("Naam :");

        spelerToevoegenGeslachtLabel.setText("Geslacht :");

        spelerToevoegenGeslachtManRadioButton.setText("Man");

        spelerToevoegenGeslachtVrouwRadioButton.setText("Vrouw");

        spelerToevoegenprofielPlaatsLabel.setText("Plaats :");

        spelerToevoegenHuisnummerLabel.setText("Huisnr. :");

        spelerToevoegenPostcodeLabel.setText("Postcode :");

        spelerToevoegenTelefoonnummerLabel.setText("Tel. nr. :");

        spelerToevoegenprofielEmailLabel.setText("E-mail :");

        spelerToevoegenClearButton.setText("Clear");
        spelerToevoegenClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spelerToevoegenClearButtonActionPerformed(evt);
            }
        });

        spelerToevoegenVoegToeButton.setText("Voeg Toe");

        spelerToevoegenAnnulerenButton.setText("Annuleren");

        javax.swing.GroupLayout spelerToevoegenLayout = new javax.swing.GroupLayout(spelerToevoegen.getContentPane());
        spelerToevoegen.getContentPane().setLayout(spelerToevoegenLayout);
        spelerToevoegenLayout.setHorizontalGroup(
            spelerToevoegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spelerToevoegenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(spelerToevoegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(spelerToevoegenLayout.createSequentialGroup()
                        .addGroup(spelerToevoegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spelerToevoegenPostcodeLabel)
                            .addComponent(spelerToevoegenTelefoonnummerLabel)
                            .addComponent(spelerToevoegenprofielEmailLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(spelerToevoegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spelerToevoegenTelefoonnummerField)
                            .addGroup(spelerToevoegenLayout.createSequentialGroup()
                                .addComponent(spelerToevoegenprofielPostcodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spelerToevoegenprofielPlaatsLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spelerToevoegenPlaatsField))
                            .addComponent(spelerToevoegenEmailField)))
                    .addGroup(spelerToevoegenLayout.createSequentialGroup()
                        .addGroup(spelerToevoegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spelerToevoegenNaamLabel)
                            .addComponent(spelerToevoegenGeslachtLabel)
                            .addComponent(spelerToevoegenStraatLabel))
                        .addGap(13, 13, 13)
                        .addGroup(spelerToevoegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(spelerToevoegenLayout.createSequentialGroup()
                                .addComponent(spelerToevoegenStraatField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spelerToevoegenHuisnummerLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spelerToevoegenHuisnummerField, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(spelerToevoegenNaamField)
                            .addGroup(spelerToevoegenLayout.createSequentialGroup()
                                .addComponent(spelerToevoegenGeslachtManRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(spelerToevoegenGeslachtVrouwRadioButton)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, spelerToevoegenLayout.createSequentialGroup()
                        .addGap(0, 153, Short.MAX_VALUE)
                        .addComponent(spelerToevoegenClearButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spelerToevoegenVoegToeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spelerToevoegenAnnulerenButton)))
                .addContainerGap())
        );
        spelerToevoegenLayout.setVerticalGroup(
            spelerToevoegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spelerToevoegenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(spelerToevoegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spelerToevoegenNaamLabel)
                    .addComponent(spelerToevoegenNaamField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(spelerToevoegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spelerToevoegenGeslachtLabel)
                    .addComponent(spelerToevoegenGeslachtManRadioButton)
                    .addComponent(spelerToevoegenGeslachtVrouwRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(spelerToevoegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spelerToevoegenStraatLabel)
                    .addComponent(spelerToevoegenHuisnummerLabel)
                    .addComponent(spelerToevoegenStraatField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spelerToevoegenHuisnummerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(spelerToevoegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spelerToevoegenPostcodeLabel)
                    .addComponent(spelerToevoegenprofielPlaatsLabel)
                    .addComponent(spelerToevoegenprofielPostcodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spelerToevoegenPlaatsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(spelerToevoegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spelerToevoegenTelefoonnummerLabel)
                    .addComponent(spelerToevoegenTelefoonnummerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(spelerToevoegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spelerToevoegenprofielEmailLabel)
                    .addComponent(spelerToevoegenEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(spelerToevoegenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spelerToevoegenAnnulerenButton)
                    .addComponent(spelerToevoegenVoegToeButton)
                    .addComponent(spelerToevoegenClearButton))
                .addContainerGap())
        );

        firstTime.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        firstTime.setTitle("Welkom");

        spelerToevoegenNaamLabel1.setText("Naam :");

        spelerToevoegenGeslachtLabel1.setText("Geslacht :");

        spelerToevoegenStraatLabel1.setText("Straat :");

        spelerToevoegenPostcodeLabel1.setText("Postcode :");

        spelerToevoegenTelefoonnummerLabel1.setText("Tel. nr. :");

        spelerToevoegenprofielEmailLabel1.setText("E-mail :");

        spelerToevoegenGeslachtManRadioButton1.setText("Man");

        spelerToevoegenGeslachtVrouwRadioButton1.setText("Vrouw");

        spelerToevoegenHuisnummerLabel1.setText("Huisnr. :");

        spelerToevoegenVoegToeButton1.setText("Clear");

        spelerToevoegenAnnulerenButton1.setText("OK");

        jLabel2.setText("Welkom bij Soccer Assistent 2000! ");

        jRadioButton1.setText("Ja, ik ben de coach");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("Nee, ik ben geen coach");

        jLabel3.setText("Bent u de coach?");

        jLabel4.setText("Plaats :");

        jLabel5.setText("Wat zijn uw gegevens?");

        javax.swing.GroupLayout firstTimeLayout = new javax.swing.GroupLayout(firstTime.getContentPane());
        firstTime.getContentPane().setLayout(firstTimeLayout);
        firstTimeLayout.setHorizontalGroup(
            firstTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstTimeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(firstTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(firstTimeLayout.createSequentialGroup()
                        .addGroup(firstTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spelerToevoegenPostcodeLabel1)
                            .addComponent(spelerToevoegenTelefoonnummerLabel1)
                            .addComponent(spelerToevoegenprofielEmailLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(firstTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spelerToevoegenTelefoonnummerField1)
                            .addGroup(firstTimeLayout.createSequentialGroup()
                                .addComponent(spelerToevoegenprofielPostcodeField1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addGap(12, 12, 12)
                                .addComponent(spelerToevoegenPlaatsField1, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                            .addComponent(spelerToevoegenEmailField1)))
                    .addGroup(firstTimeLayout.createSequentialGroup()
                        .addGroup(firstTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spelerToevoegenNaamLabel1)
                            .addComponent(spelerToevoegenGeslachtLabel1)
                            .addComponent(spelerToevoegenStraatLabel1))
                        .addGap(13, 13, 13)
                        .addGroup(firstTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(firstTimeLayout.createSequentialGroup()
                                .addComponent(spelerToevoegenStraatField1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spelerToevoegenHuisnummerLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spelerToevoegenHuisnummerField1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(spelerToevoegenNaamField1)
                            .addGroup(firstTimeLayout.createSequentialGroup()
                                .addComponent(spelerToevoegenGeslachtManRadioButton1)
                                .addGap(18, 18, 18)
                                .addComponent(spelerToevoegenGeslachtVrouwRadioButton1)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, firstTimeLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(spelerToevoegenVoegToeButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spelerToevoegenAnnulerenButton1))
                    .addGroup(firstTimeLayout.createSequentialGroup()
                        .addGroup(firstTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(firstTimeLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(firstTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton2)
                                    .addComponent(jRadioButton1)))
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        firstTimeLayout.setVerticalGroup(
            firstTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstTimeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(1, 1, 1)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(firstTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spelerToevoegenNaamLabel1)
                    .addComponent(spelerToevoegenNaamField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(firstTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spelerToevoegenGeslachtLabel1)
                    .addComponent(spelerToevoegenGeslachtManRadioButton1)
                    .addComponent(spelerToevoegenGeslachtVrouwRadioButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(firstTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spelerToevoegenStraatLabel1)
                    .addComponent(spelerToevoegenHuisnummerLabel1)
                    .addComponent(spelerToevoegenStraatField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spelerToevoegenHuisnummerField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(firstTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spelerToevoegenPostcodeLabel1)
                    .addComponent(spelerToevoegenprofielPostcodeField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spelerToevoegenPlaatsField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(firstTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spelerToevoegenTelefoonnummerLabel1)
                    .addComponent(spelerToevoegenTelefoonnummerField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(firstTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spelerToevoegenprofielEmailLabel1)
                    .addComponent(spelerToevoegenEmailField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(firstTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spelerToevoegenAnnulerenButton1)
                    .addComponent(spelerToevoegenVoegToeButton1))
                .addContainerGap())
        );

        wedstrijdTeamAanmaken.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        wedstrijdTeamAanmaken.setTitle("Wedstrijd Team Aanmaken");

        wedstrijdTeamAanmakenGekozenTeamList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        wedstrijdTeamAanmakenGekozenTeamScrollPane.setViewportView(wedstrijdTeamAanmakenGekozenTeamList);

        wedstrijdTeamAanmakenBeschikbareSpelersList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        wedstrijdTeamAanmakenBeschikbareSpelersScrollPane.setViewportView(wedstrijdTeamAanmakenBeschikbareSpelersList);

        wedstrijdTeamAanmakenBeschikbareSpelersLabel.setText("Beschikbare spelers");

        wedstrijdTeamAanmakenGekozenTeamLabel.setText("Gekozen team");

        wedstrijdTeamAanmakenKiesButton.setText("Kies voor team");

        wedstrijdTeamAanmakenVerwijderButton.setText("Verwijder uit team");

        wedstrijdTeamAanmakenAnnulerenButton.setText("Annuleren");

        wedstrijdTeamAanmakenOpslaanButton.setText("Opslaan");

        javax.swing.GroupLayout wedstrijdTeamAanmakenLayout = new javax.swing.GroupLayout(wedstrijdTeamAanmaken.getContentPane());
        wedstrijdTeamAanmaken.getContentPane().setLayout(wedstrijdTeamAanmakenLayout);
        wedstrijdTeamAanmakenLayout.setHorizontalGroup(
            wedstrijdTeamAanmakenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wedstrijdTeamAanmakenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(wedstrijdTeamAanmakenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wedstrijdTeamAanmakenLayout.createSequentialGroup()
                        .addGroup(wedstrijdTeamAanmakenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(wedstrijdTeamAanmakenLayout.createSequentialGroup()
                                .addComponent(wedstrijdTeamAanmakenBeschikbareSpelersScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(wedstrijdTeamAanmakenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(wedstrijdTeamAanmakenVerwijderButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(wedstrijdTeamAanmakenKiesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(wedstrijdTeamAanmakenLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(wedstrijdTeamAanmakenBeschikbareSpelersLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(wedstrijdTeamAanmakenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(wedstrijdTeamAanmakenGekozenTeamScrollPane)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, wedstrijdTeamAanmakenLayout.createSequentialGroup()
                                .addGap(0, 47, Short.MAX_VALUE)
                                .addComponent(wedstrijdTeamAanmakenGekozenTeamLabel)
                                .addGap(35, 35, 35))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, wedstrijdTeamAanmakenLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(wedstrijdTeamAanmakenOpslaanButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wedstrijdTeamAanmakenAnnulerenButton)))
                .addContainerGap())
        );
        wedstrijdTeamAanmakenLayout.setVerticalGroup(
            wedstrijdTeamAanmakenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wedstrijdTeamAanmakenLayout.createSequentialGroup()
                .addGroup(wedstrijdTeamAanmakenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wedstrijdTeamAanmakenLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(wedstrijdTeamAanmakenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(wedstrijdTeamAanmakenBeschikbareSpelersLabel)
                            .addComponent(wedstrijdTeamAanmakenGekozenTeamLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(wedstrijdTeamAanmakenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(wedstrijdTeamAanmakenBeschikbareSpelersScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                            .addComponent(wedstrijdTeamAanmakenGekozenTeamScrollPane))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(wedstrijdTeamAanmakenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(wedstrijdTeamAanmakenAnnulerenButton)
                            .addComponent(wedstrijdTeamAanmakenOpslaanButton)))
                    .addGroup(wedstrijdTeamAanmakenLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(wedstrijdTeamAanmakenKiesButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wedstrijdTeamAanmakenVerwijderButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Soccer Assistent 2000");

        javax.swing.GroupLayout welkomTabLayout = new javax.swing.GroupLayout(welkomTab);
        welkomTab.setLayout(welkomTabLayout);
        welkomTabLayout.setHorizontalGroup(
            welkomTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 468, Short.MAX_VALUE)
        );
        welkomTabLayout.setVerticalGroup(
            welkomTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 227, Short.MAX_VALUE)
        );

        tabbedPane.addTab("Welkom", welkomTab);

        profielNaamLabel.setText("Naam :");

        profielGeslachtLabel.setText("Geslacht :");

        profielStraatLabel.setText("Straat :");

        profielHuisnummerLabel.setText("Huisnr. :");

        profielPostcodeLabel.setText("Postcode :");

        profielPlaatsLabel.setText("Plaats :");

        profielTelefoonnummerLabel.setText("Tel. nr. :");

        profielEmailLabel.setText("E-mail :");

        profielGeslachtManRadioButton.setText("Man");

        profielGeslachtVrouwRadioButton.setText("Vrouw");

        profielLoguitButton.setText("Log uit");

        profielWijzigButton.setText("Wijzig");

        profielLoginGegevensButton.setText("Login Gegevens");
        profielLoginGegevensButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profielLoginGegevensButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout profielTabLayout = new javax.swing.GroupLayout(profielTab);
        profielTab.setLayout(profielTabLayout);
        profielTabLayout.setHorizontalGroup(
            profielTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profielTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(profielTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profielTabLayout.createSequentialGroup()
                        .addGroup(profielTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(profielPostcodeLabel)
                            .addComponent(profielTelefoonnummerLabel)
                            .addComponent(profielEmailLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(profielTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(profielTelefoonnummerField)
                            .addGroup(profielTabLayout.createSequentialGroup()
                                .addComponent(profielPostcodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(profielPlaatsLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(profielPlaatsField))
                            .addComponent(profielEmailField)))
                    .addGroup(profielTabLayout.createSequentialGroup()
                        .addGroup(profielTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(profielNaamLabel)
                            .addComponent(profielGeslachtLabel)
                            .addComponent(profielStraatLabel))
                        .addGap(13, 13, 13)
                        .addGroup(profielTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(profielTabLayout.createSequentialGroup()
                                .addComponent(profielStraatField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(profielHuisnummerLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(profielHuisnummerField, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(profielNaamField)
                            .addGroup(profielTabLayout.createSequentialGroup()
                                .addComponent(profielGeslachtManRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(profielGeslachtVrouwRadioButton)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profielTabLayout.createSequentialGroup()
                        .addGap(0, 201, Short.MAX_VALUE)
                        .addComponent(profielLoginGegevensButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(profielWijzigButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(profielLoguitButton)))
                .addContainerGap())
        );
        profielTabLayout.setVerticalGroup(
            profielTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profielTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(profielTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profielNaamLabel)
                    .addComponent(profielNaamField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(profielTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profielGeslachtLabel)
                    .addComponent(profielGeslachtManRadioButton)
                    .addComponent(profielGeslachtVrouwRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(profielTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profielStraatLabel)
                    .addComponent(profielHuisnummerLabel)
                    .addComponent(profielStraatField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profielHuisnummerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(profielTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profielPostcodeLabel)
                    .addComponent(profielPlaatsLabel)
                    .addComponent(profielPostcodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profielPlaatsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(profielTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profielTelefoonnummerLabel)
                    .addComponent(profielTelefoonnummerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(profielTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profielEmailLabel)
                    .addComponent(profielEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(profielTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profielLoguitButton)
                    .addComponent(profielWijzigButton)
                    .addComponent(profielLoginGegevensButton))
                .addContainerGap())
        );

        tabbedPane.addTab("Profiel", profielTab);

        beschikbaarheidWedstrijdenList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        beschikbaarheidWedstrijdenScrollPane.setViewportView(beschikbaarheidWedstrijdenList);

        jLabel6.setText("Je bent beschikbaar voor de volgende wedstrijden:");

        javax.swing.GroupLayout beschikbaarheidTabLayout = new javax.swing.GroupLayout(beschikbaarheidTab);
        beschikbaarheidTab.setLayout(beschikbaarheidTabLayout);
        beschikbaarheidTabLayout.setHorizontalGroup(
            beschikbaarheidTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(beschikbaarheidTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(beschikbaarheidTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(beschikbaarheidWedstrijdenScrollPane)
                    .addGroup(beschikbaarheidTabLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 202, Short.MAX_VALUE)))
                .addContainerGap())
        );
        beschikbaarheidTabLayout.setVerticalGroup(
            beschikbaarheidTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(beschikbaarheidTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(beschikbaarheidWedstrijdenScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPane.addTab("Beschikbaarheid", beschikbaarheidTab);

        statistiekenToevoegenToevoegenButton.setText("Toevoegen");

        statistiekenToevoegenClearButton.setText("Clear");

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout statistiekenToevoegenTabLayout = new javax.swing.GroupLayout(statistiekenToevoegenTab);
        statistiekenToevoegenTab.setLayout(statistiekenToevoegenTabLayout);
        statistiekenToevoegenTabLayout.setHorizontalGroup(
            statistiekenToevoegenTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statistiekenToevoegenTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statistiekenToevoegenTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statistiekenToevoegenTabLayout.createSequentialGroup()
                        .addGap(0, 298, Short.MAX_VALUE)
                        .addComponent(statistiekenToevoegenClearButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statistiekenToevoegenToevoegenButton))
                    .addGroup(statistiekenToevoegenTabLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        statistiekenToevoegenTabLayout.setVerticalGroup(
            statistiekenToevoegenTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statistiekenToevoegenTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                .addGroup(statistiekenToevoegenTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statistiekenToevoegenToevoegenButton)
                    .addComponent(statistiekenToevoegenClearButton))
                .addContainerGap())
        );

        tabbedPane.addTab("Statistieken Toevoegen", statistiekenToevoegenTab);

        teamSpelerToevoegenButton.setText("Speler Toevoegen");

        teamWedstrijdToevoegenButton.setText("Wedstrijd Toevoegen");

        teamCapainAanwijzenButton.setText("Captain Aanwijzen");

        teamKeeperAanwijzenButton.setText("Keeper Aanwijzen");

        teamSpelerOpvragenButton.setText("Speler Opvragen");

        teamWedstrijdTeamAanmakenButton.setText("Wedstrijd Team Aanmaken");

        teamWedstrijdTeamWijzigenButton.setText("Wedstrijd Team Wijzigen");

        teamTeamLabel.setText("Team");

        teamWedstrijdLabel.setText("Wedstrijd");

        teamStatistiekenBekijkenButton.setText("Statistieken bekijken");

        teamAankomendeWedstrijdenButton.setText("Aankomende Wedstrijden");

        javax.swing.GroupLayout teamTabLayout = new javax.swing.GroupLayout(teamTab);
        teamTab.setLayout(teamTabLayout);
        teamTabLayout.setHorizontalGroup(
            teamTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teamTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(teamTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, teamTabLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(teamStatistiekenBekijkenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(teamTabLayout.createSequentialGroup()
                        .addGroup(teamTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(teamSpelerToevoegenButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(teamCapainAanwijzenButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(teamKeeperAanwijzenButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(teamTabLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(teamTeamLabel))
                            .addComponent(teamSpelerOpvragenButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                        .addGroup(teamTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, teamTabLayout.createSequentialGroup()
                                .addGroup(teamTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(teamWedstrijdTeamWijzigenButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(teamAankomendeWedstrijdenButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(teamWedstrijdToevoegenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, teamTabLayout.createSequentialGroup()
                                .addComponent(teamWedstrijdLabel)
                                .addGap(63, 63, 63))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, teamTabLayout.createSequentialGroup()
                                .addComponent(teamWedstrijdTeamAanmakenButton)
                                .addContainerGap())))))
        );
        teamTabLayout.setVerticalGroup(
            teamTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teamTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(teamTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teamTeamLabel)
                    .addComponent(teamWedstrijdLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(teamTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teamSpelerToevoegenButton)
                    .addComponent(teamAankomendeWedstrijdenButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(teamTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teamCapainAanwijzenButton)
                    .addComponent(teamWedstrijdToevoegenButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(teamTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teamKeeperAanwijzenButton)
                    .addComponent(teamWedstrijdTeamAanmakenButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(teamTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teamSpelerOpvragenButton)
                    .addComponent(teamWedstrijdTeamWijzigenButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teamStatistiekenBekijkenButton)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Team", teamTab);

        optionsMenu.setText("Options");
        optionsMenu.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                optionsMenuComponentHidden(evt);
            }
        });

        logoffMenuItem.setText("Log uit");
        optionsMenu.add(logoffMenuItem);

        loginMenuItem.setText("Log in");
        optionsMenu.add(loginMenuItem);

        toggleFullscreenMenuItem.setSelected(true);
        toggleFullscreenMenuItem.setText("Fullscreen");
        optionsMenu.add(toggleFullscreenMenuItem);

        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        optionsMenu.add(exitMenuItem);

        menuBar.add(optionsMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        // TODO add your handling code here:save and exit
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void profielLoginGegevensButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profielLoginGegevensButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profielLoginGegevensButtonActionPerformed

    private void spelerToevoegenClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spelerToevoegenClearButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spelerToevoegenClearButtonActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void optionsMenuComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_optionsMenuComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_optionsMenuComponentHidden

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginGegevensOKButton;
    private javax.swing.JPanel beschikbaarheidTab;
    private javax.swing.JList beschikbaarheidWedstrijdenList;
    private javax.swing.JScrollPane beschikbaarheidWedstrijdenScrollPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JDialog firstTime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JDialog loginGegevens;
    private javax.swing.JTextField loginGegevensGebruikersnaamField;
    private javax.swing.JLabel loginGegevensGebruikersnaamLabel;
    private javax.swing.JTextField loginGegevensWachtwoordField;
    private javax.swing.JLabel loginGegevensWachtwoordPanel;
    private javax.swing.JButton loginGegevensWijzigButton;
    private javax.swing.JMenuItem loginMenuItem;
    private javax.swing.JMenuItem logoffMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu optionsMenu;
    private javax.swing.JTextField profielEmailField;
    private javax.swing.JLabel profielEmailLabel;
    private javax.swing.JLabel profielGeslachtLabel;
    private javax.swing.JRadioButton profielGeslachtManRadioButton;
    private javax.swing.JRadioButton profielGeslachtVrouwRadioButton;
    private javax.swing.JTextField profielHuisnummerField;
    private javax.swing.JLabel profielHuisnummerLabel;
    private javax.swing.JButton profielLoginGegevensButton;
    private javax.swing.JButton profielLoguitButton;
    private javax.swing.JTextField profielNaamField;
    private javax.swing.JLabel profielNaamLabel;
    private javax.swing.JTextField profielPlaatsField;
    private javax.swing.JLabel profielPlaatsLabel;
    private javax.swing.JTextField profielPostcodeField;
    private javax.swing.JLabel profielPostcodeLabel;
    private javax.swing.JTextField profielStraatField;
    private javax.swing.JLabel profielStraatLabel;
    private javax.swing.JPanel profielTab;
    private javax.swing.JTextField profielTelefoonnummerField;
    private javax.swing.JLabel profielTelefoonnummerLabel;
    private javax.swing.JButton profielWijzigButton;
    private javax.swing.JDialog spelerToevoegen;
    private javax.swing.JButton spelerToevoegenAnnulerenButton;
    private javax.swing.JButton spelerToevoegenAnnulerenButton1;
    private javax.swing.JButton spelerToevoegenClearButton;
    private javax.swing.JTextField spelerToevoegenEmailField;
    private javax.swing.JTextField spelerToevoegenEmailField1;
    private javax.swing.JLabel spelerToevoegenGeslachtLabel;
    private javax.swing.JLabel spelerToevoegenGeslachtLabel1;
    private javax.swing.JRadioButton spelerToevoegenGeslachtManRadioButton;
    private javax.swing.JRadioButton spelerToevoegenGeslachtManRadioButton1;
    private javax.swing.JRadioButton spelerToevoegenGeslachtVrouwRadioButton;
    private javax.swing.JRadioButton spelerToevoegenGeslachtVrouwRadioButton1;
    private javax.swing.JTextField spelerToevoegenHuisnummerField;
    private javax.swing.JTextField spelerToevoegenHuisnummerField1;
    private javax.swing.JLabel spelerToevoegenHuisnummerLabel;
    private javax.swing.JLabel spelerToevoegenHuisnummerLabel1;
    private javax.swing.JTextField spelerToevoegenNaamField;
    private javax.swing.JTextField spelerToevoegenNaamField1;
    private javax.swing.JLabel spelerToevoegenNaamLabel;
    private javax.swing.JLabel spelerToevoegenNaamLabel1;
    private javax.swing.JTextField spelerToevoegenPlaatsField;
    private javax.swing.JTextField spelerToevoegenPlaatsField1;
    private javax.swing.JLabel spelerToevoegenPostcodeLabel;
    private javax.swing.JLabel spelerToevoegenPostcodeLabel1;
    private javax.swing.JTextField spelerToevoegenStraatField;
    private javax.swing.JTextField spelerToevoegenStraatField1;
    private javax.swing.JLabel spelerToevoegenStraatLabel;
    private javax.swing.JLabel spelerToevoegenStraatLabel1;
    private javax.swing.JTextField spelerToevoegenTelefoonnummerField;
    private javax.swing.JTextField spelerToevoegenTelefoonnummerField1;
    private javax.swing.JLabel spelerToevoegenTelefoonnummerLabel;
    private javax.swing.JLabel spelerToevoegenTelefoonnummerLabel1;
    private javax.swing.JButton spelerToevoegenVoegToeButton;
    private javax.swing.JButton spelerToevoegenVoegToeButton1;
    private javax.swing.JLabel spelerToevoegenprofielEmailLabel;
    private javax.swing.JLabel spelerToevoegenprofielEmailLabel1;
    private javax.swing.JLabel spelerToevoegenprofielPlaatsLabel;
    private javax.swing.JTextField spelerToevoegenprofielPostcodeField;
    private javax.swing.JTextField spelerToevoegenprofielPostcodeField1;
    private javax.swing.JButton statistiekenToevoegenClearButton;
    private javax.swing.JPanel statistiekenToevoegenTab;
    private javax.swing.JButton statistiekenToevoegenToevoegenButton;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JButton teamAankomendeWedstrijdenButton;
    private javax.swing.JButton teamCapainAanwijzenButton;
    private javax.swing.JButton teamKeeperAanwijzenButton;
    private javax.swing.JButton teamSpelerOpvragenButton;
    private javax.swing.JButton teamSpelerToevoegenButton;
    private javax.swing.JButton teamStatistiekenBekijkenButton;
    private javax.swing.JPanel teamTab;
    private javax.swing.JLabel teamTeamLabel;
    private javax.swing.JLabel teamWedstrijdLabel;
    private javax.swing.JButton teamWedstrijdTeamAanmakenButton;
    private javax.swing.JButton teamWedstrijdTeamWijzigenButton;
    private javax.swing.JButton teamWedstrijdToevoegenButton;
    private javax.swing.JRadioButtonMenuItem toggleFullscreenMenuItem;
    private javax.swing.JDialog wedstrijdTeamAanmaken;
    private javax.swing.JButton wedstrijdTeamAanmakenAnnulerenButton;
    private javax.swing.JLabel wedstrijdTeamAanmakenBeschikbareSpelersLabel;
    private javax.swing.JList wedstrijdTeamAanmakenBeschikbareSpelersList;
    private javax.swing.JScrollPane wedstrijdTeamAanmakenBeschikbareSpelersScrollPane;
    private javax.swing.JLabel wedstrijdTeamAanmakenGekozenTeamLabel;
    private javax.swing.JList wedstrijdTeamAanmakenGekozenTeamList;
    private javax.swing.JScrollPane wedstrijdTeamAanmakenGekozenTeamScrollPane;
    private javax.swing.JButton wedstrijdTeamAanmakenKiesButton;
    private javax.swing.JButton wedstrijdTeamAanmakenOpslaanButton;
    private javax.swing.JButton wedstrijdTeamAanmakenVerwijderButton;
    private javax.swing.JPanel welkomTab;
    // End of variables declaration//GEN-END:variables
}
